FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    make git build-essential \
    python3 \
    gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /ws
