#ifndef LOG_H
#define LOG_H

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {

#endif


/* Convenience init for bare-metal UART platform.
 * Implemented in log_baremetal.cpp.
 * Call this once after Global::uart has been configured.
 */
void log_init_baremetal(void);


/*===========================================================
 *  SIMPLE LOGGING SYSTEM
 *
 *  USAGE EXAMPLE 1: Bare-metal with UART
 *  ------------------------------------
 *
 *  // log_config.h (optional, before including log.h)
 *  #define LOG_COMPILE_LEVEL    LOG_LEVEL_DEBUG
 *  #define LOG_ENABLE_TIMESTAMP 1
 *  #define LOG_USE_RING_BUFFER  1
 *
 *  // uart.c
 *  void uart_init(void);
 *  void uart_putc(char c);
 *
 *  static void uart_log_write(const char *buf, size_t len)
 *  {
 *      for (size_t i = 0; i < len; ++i)
 *          uart_putc(buf[i]);
 *  }
 *
 *  // Simple timestamp in ms (e.g. from a SysTick handler)
 *  extern volatile uint32_t g_tick_ms;
 *  static uint32_t log_get_time_ms(void)
 *  {
 *      return g_tick_ms;
 *  }
 *
 *  // main.c
 *  #include "log.h"
 *
 *  int main(void)
 *  {
 *      uart_init();
 *
 *      log_init(uart_log_write);
 *      log_set_level(LOG_LEVEL_DEBUG);           // runtime level
 *  #if LOG_ENABLE_TIMESTAMP
 *      log_set_timestamp_fn(log_get_time_ms);    // optional
 *  #endif
 *
 *      pr_info("System boot, hw_id=0x%08X", hw_id());
 *      pr_debug("Clock=%u Hz", (unsigned)get_sysclk());
 *
 *      uint8_t rx[32] = { 1, 2, 3, 4 };
 *      pr_hexdump(LOG_LEVEL_DEBUG, "RX: ", rx, sizeof(rx));
 *
 *      for (;;)
 *          ; // main loop
 *  }
 *
 *  USAGE EXAMPLE 2: Hosted / Linux with stderr (libc)
 *  --------------------------------------------------
 *
 *  #include <stdio.h>
 *  #include <time.h>
 *  #include <unistd.h>   // for getpid()
 *  #include "log.h"
 *
 *  static void stderr_log_write(const char *buf, size_t len)
 *  {
 *      fwrite(buf, 1, len, stderr);
 *      fflush(stderr);   // optional
 *  }
 *
 *  static uint32_t log_get_time_ms(void)
 *  {
 *      struct timespec ts;
 *      clock_gettime(CLOCK_REALTIME, &ts);
 *      uint64_t ms = (uint64_t)ts.tv_sec * 1000u + ts.tv_nsec / 1000000u;
 *      return (uint32_t)(ms & 0xFFFFFFFFu);
 *  }
 *
 *  int main(void)
 *  {
 *      log_init(stderr_log_write);
 *      log_set_level(LOG_LEVEL_DEBUG);
 *  #if LOG_ENABLE_TIMESTAMP
 *      log_set_timestamp_fn(log_get_time_ms);
 *  #endif
 *
 *      pr_info("hello from log system, pid=%d", (int)getpid());
 *      pr_warn("this is a warning");
 *      pr_err("something failed: code=%d", -1);
 *
 *      log_set_level(LOG_LEVEL_INFO);  // now DEBUG/TRACE won't show
 *      pr_debug("you should NOT see this");
 *      pr_info("but you WILL see this");
 *
 *      return 0;
 *  }
 *
 *===========================================================*/

/* =========================
 *   CONFIGURATION MACROS
 * ========================= */

/* Log levels (similar to kernel) */
typedef enum {
  LOG_LEVEL_OFF = 0,
  LOG_LEVEL_ERROR = 1,
  LOG_LEVEL_WARN = 2,
  LOG_LEVEL_INFO = 3,
  LOG_LEVEL_DEBUG = 4,
  LOG_LEVEL_TRACE = 5,
} log_level_t;

/* Max level that is compiled in (compile-time filter). */
#ifndef LOG_COMPILE_LEVEL
#define LOG_COMPILE_LEVEL LOG_LEVEL_DEBUG
#endif

/* Default runtime level (can be changed with log_set_level). */
#ifndef LOG_RUNTIME_DEFAULT_LEVEL
#define LOG_RUNTIME_DEFAULT_LEVEL LOG_LEVEL_INFO
#endif

/* Controls how the 'file' component (from __FILE__) is printed. */
typedef enum {
  LOG_PATH_NONE = 0,     /* do not print file at all */
  LOG_PATH_BASENAME = 1, /* print only basename, e.g. "minit.cpp" */
  LOG_PATH_FULL = 2,     /* print full __FILE__ string */
} log_path_mode_t;

#ifndef LOG_DEFAULT_PATH_MODE
#define LOG_DEFAULT_PATH_MODE LOG_PATH_BASENAME
#endif // LOG_DEFAULT_PATH_MODE

/* Enable/disable timestamp support. */
#ifndef LOG_ENABLE_TIMESTAMP
#define LOG_ENABLE_TIMESTAMP 1
#endif

/* Enable/disable in-RAM ring buffer. */
#ifndef LOG_USE_RING_BUFFER
#define LOG_USE_RING_BUFFER 1
#endif

/* Size of temporary formatting buffer for one log line. */
#ifndef LOG_BUFFER_SIZE
#define LOG_BUFFER_SIZE 256
#endif

/* Ring buffer size in bytes (for storing log output). */
#ifndef LOG_RING_BUFFER_SIZE
#define LOG_RING_BUFFER_SIZE 2048
#endif

/* =========================
 *        TYPES & API
 * ========================= */

/* Low-level writer: you implement this (e.g. UART, SWO, semihosting). */
typedef void (*log_write_fn_t)(const char* buf, size_t len);

/* Initialize logging with a writer (must be called before using pr_*). */
void log_init(log_write_fn_t fn);

/* Runtime level control. */
void log_set_level(log_level_t level);
log_level_t log_get_level(void);

/* Control whether and how file paths are printed. */
void log_set_path_mode(log_path_mode_t mode);
log_path_mode_t log_get_path_mode(void);

/* Convert level to short string ("E", "W", "I", "D", "T"). */
const char* log_level_to_string(log_level_t level);

/* Core logging functions (normally use pr_* macros instead). */
int log_vprintf(log_level_t level, const char* file, int line, const char* func,
                const char* fmt, va_list ap);

int log_printf(log_level_t level, const char* file, int line, const char* func,
               const char* fmt, ...);

/* ===== Timestamps ===== */
#if LOG_ENABLE_TIMESTAMP
/* Timestamp callback: return time in ticks or ms, up to you. */
typedef uint32_t (*log_timestamp_fn_t)(void);

/* Set timestamp provider. If NULL, no timestamp is printed. */
void log_set_timestamp_fn(log_timestamp_fn_t fn);
#endif /* LOG_ENABLE_TIMESTAMP */

/* ===== Ring buffer access (kernel-like log buffer) ===== */
#if LOG_USE_RING_BUFFER
/* Read and consume up to maxlen bytes from ring buffer. */
size_t log_ring_read(char* out, size_t maxlen);

/* Peek (non-destructive) up to maxlen bytes from ring buffer. */
size_t log_ring_peek(char* out, size_t maxlen);

/* Current used size and total capacity of ring buffer. */
size_t log_ring_size(void);
size_t log_ring_capacity(void);

/* Clear the ring buffer. */
void log_ring_clear(void);
#endif /* LOG_USE_RING_BUFFER */

/* ===== Hexdump helper ===== */

/* Hexdump with log prefix (level/file/line/func etc). */
void log_hexdump(log_level_t level, const char* file, int line,
                 const char* func, const void* data, size_t len,
                 const char* prefix);

/* =========================
 *   LOCKING HOOKS
 * ========================= */

/* Optional lock/unlock hooks for multi-core/IRQ safety.
 * You can override these macros before including log.h, e.g.:
 *
 *   #define LOG_LOCK()   uint32_t flags = irq_disable()
 *   #define LOG_UNLOCK() irq_restore(flags)
 */
#ifndef LOG_LOCK
#define LOG_LOCK()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

#ifndef LOG_UNLOCK
#define LOG_UNLOCK()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

/* =========================
 *       PRINT MACROS
 * ========================= */

/* Internal helper: do not use directly. */
#define LOG_DO_PRINT(level, fmt, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
        if ((level) <= LOG_COMPILE_LEVEL)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
            log_printf((level), __FILE__, __LINE__, __func__, fmt, ##__VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    } while (0)

/* printk-style macros */
#if LOG_COMPILE_LEVEL >= LOG_LEVEL_ERROR
#define pr_err(fmt, ...) LOG_DO_PRINT(LOG_LEVEL_ERROR, fmt, ##__VA_ARGS__)
#else
#define pr_err(fmt, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

#if LOG_COMPILE_LEVEL >= LOG_LEVEL_WARN
#define pr_warn(fmt, ...) LOG_DO_PRINT(LOG_LEVEL_WARN, fmt, ##__VA_ARGS__)
#else
#define pr_warn(fmt, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

#if LOG_COMPILE_LEVEL >= LOG_LEVEL_INFO
#define pr_info(fmt, ...) LOG_DO_PRINT(LOG_LEVEL_INFO, fmt, ##__VA_ARGS__)
#else
#define pr_info(fmt, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

#if LOG_COMPILE_LEVEL >= LOG_LEVEL_DEBUG
#define pr_debug(fmt, ...) LOG_DO_PRINT(LOG_LEVEL_DEBUG, fmt, ##__VA_ARGS__)
#else
#define pr_debug(fmt, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

#if LOG_COMPILE_LEVEL >= LOG_LEVEL_TRACE
#define pr_trace(fmt, ...) LOG_DO_PRINT(LOG_LEVEL_TRACE, fmt, ##__VA_ARGS__)
#else
#define pr_trace(fmt, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    } while (0)
#endif

/* Hexdump macro.
 * 'level' is one of LOG_LEVEL_*, 'prefix' can be NULL or a short string.
 */
#define pr_hexdump(level, prefix, data, length)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \
    do                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
        if ((level) <= LOG_COMPILE_LEVEL)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
            log_hexdump((level), __FILE__, __LINE__, __func__, (data), (length), (prefix));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    } while (0)

#ifdef __cplusplus
}
#endif

#endif /* LOG_H */
