#ifndef BAREMETAL_KERNEL_CONFIG_H
#define BAREMETAL_KERNEL_CONFIG_H

#include "log_config.h"

#define KSTACK_SIZE 4096  // 每个 hart 4KB 栈

#define KERNEL_STACK_SIZE 4096
#define THREAD_STACK_SIZE 4096
#define THREAD_MAX 10

#endif //BAREMETAL_KERNEL_CONFIG_H
