#ifndef BAREMETAL_LOG_CONFIG_H
#define BAREMETAL_LOG_CONFIG_H

#define LOG_COMPILE_LEVEL         LOG_LEVEL_DEBUG
#define LOG_RUNTIME_DEFAULT_LEVEL LOG_LEVEL_DEBUG
#define LOG_DEFAULT_PATH_MODE     LOG_PATH_BASENAME
#define LOG_ENABLE_TIMESTAMP      1

#endif  // BAREMETAL_LOG_CONFIG_H
